import type { Metadata } from "next";
import "@styles/globals.css";
import "@radix-ui/themes/styles.css";
import ThemeWrapper from "@components/ThemeWrapper";

export const metadata: Metadata = {
	title: "Tree Task Manager App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body className="antialiased">
				<ThemeWrapper>{children}</ThemeWrapper>
			</body>
		</html>
	);
}
