import type { Metadata } from "next";
import "@/src/styles/globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
	title: "Tree Task Manager App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body className="antialiased">
				<Theme>{children}</Theme>
			</body>
		</html>
	);
}
